### ISSUE TITLE
Binary is detected as malicious by Avira/VirusTotal (2/68)

### ISSUE THREAD

**Issue by ghost** [Dakror/UnicodeInput#1]
https://www.virustotal.com/#/file/c98d1381740e3dd0cb48f60b99bf2f0b00c545577c35565689e1eed01c895c7c/detection

Specifically, TR/Crypt.XPACK.Gen7

**Comment by Dakror** [comment]
Well technically its a keylogger. so that wont change.

If you don't trust the executable, you're welcome to compile it yourself.
